### ISSUE TITLE
v0.1.1版本运行一段时间后会出现err io: read/write on closed pipe导致转发中断

### ISSUE THREAD

**Issue by ron777-777** [Ehco1996/ehco#12]
![image](https://user-images.githubusercontent.com/57038401/86535896-263dee00-bf16-11ea-9062-3348448686b0.png)
用回v0.1.0版本则正常

**Comment by Ehco1996** [comment]
因为加了一个主动的关闭的10分钟的Deadline
断流的现象很严重么？

**Comment by Neurotoxinw** [comment]
我也有遇到
断流还挺严重的

**Comment by Ehco1996** [comment]
@ron777-777 @Neurotoxinw 

我大概找到问题了，预计这两天会出一个修复版本

**Comment by Num0** [comment]
我也发现了类似的问题，升了0.1.2也依旧存在

**Comment by Ehco1996** [comment]
@ron777-777  @Neurotoxinw 

可以升级到0.1.3 试试，应该能解决掉部分断流的情况
 https://github.com/Ehco1996/ehco/releases/tag/v0.1.3

**Comment by Neurotoxinw** [comment]
@Ehco1996 0.1.3用了一天挺好的 没有这个问题了
