### ISSUE TITLE
Support go 1.19 build

### ISSUE THREAD

**Issue by chenrui333** [Ehco1996/ehco#165]
Need to [upgrade quic-go to 0.28.0+](https://github.com/lucas-clemente/quic-go/issues/3491) to be able to build with go@1.19

relates to https://github.com/Homebrew/homebrew-core/pull/115670

**Comment by Ehco1996** [comment]
thank for mention this， i will try bump go version and brew version when i have enough free time (maybe next weekend 😬)

But feel open a pr here if you want to, i will very happy to review 😬

**Comment by chenrui333** [comment]
yeah, I have managed to build the formula with go1.18, I will try to see if I can help with go1.19 upgrade 🍻

**Comment by Ehco1996** [comment]
closed by https://github.com/Ehco1996/ehco/commit/bde88043efb6d0f0882d0a224de326407894009d
