### ISSUE TITLE
端口监听和负载均衡的需求

### ISSUE THREAD

**Issue by ghost** [Ehco1996/ehco#18]
配置文件中configs的一个数组里多个 listen 只生效最后一个，希望可以对端口监听改进下，和监听IP分开，可以区间监听，类似于V2ray，或者可以全部生效
希望大佬可以加上负载均衡，比如多个 remote 会轮询

**Comment by Ehco1996** [comment]
多个listen是都生效的。

一个listen目前是支持多个remote的负载均衡的
