### ISSUE TITLE
请问是否支持隧道转发？执行命令该如何写？

### ISSUE THREAD

**Issue by 171621** [Ehco1996/ehco#20]
请问是否支持在服务器A与B之间建立隧道 再将A发到B的数据通过B转发给C？或将C传输给B的数据通过AB间的隧道传回给A？如果支持的话命令该如何写呢？

**Comment by Ehco1996** [comment]
支持链式转发的

给abc都起一个ehco
a->b-c 就可以了

**Comment by 171621** [comment]
> 支持链式转发的
> 
> 给abc都起一个ehco
> a->b-c 就可以了

哦 那是不是可以这样：比如中转A机器1111端口转发 ，中转B机器b.b.b.b:2222转发，落地C机器c.c.c.c:3333端口接收，SS/v2ray服务端口443，三台机器都部署ehco之后分别做如下设置：

A: ehco -l 0.0.0.0:1111 -r wss://b.b.b.b:2222 -tt wss
B: ehco -l 0.0.0.0:2222 -lt wss -r c.c.c.c:3333
C: ehco -l 0.0.0.0:3333 -r 127.0.0.1:443

B与C之间不用加密，请问是这样配置吗？

**Comment by Ehco1996** [comment]
1. 对
2。 可以用systemd或者docker
