### ISSUE TITLE
Support go1.20.x/1.21.0 build

### ISSUE THREAD

**Issue by chenrui333** [Ehco1996/ehco#225]
👋 Now go1.19 is EOL, need to bump xray to support go1.20 build. 

need to wait for https://github.com/v2fly/v2ray-core/issues/2644 to be fixed for bumping to build with go1.21.0

relates to https://github.com/Homebrew/homebrew-core/pull/139431

**Comment by Ehco1996** [comment]
thanks  already fixed

**Comment by chenrui333** [comment]
@Ehco1996 thanks, mind cutting a new release to refresh the downstream packaging stuff?
