### ISSUE TITLE
使用dockerfile建立image后没有在readme中找到环境变量

### ISSUE THREAD

**Issue by olperson** [Ehco1996/ehco#24]
请问使用docker运行方式保持后台运行是需要进入docker运行ehco类似这些命令：`**ehco -l 0.0.0.0:1234 -r 2.2.2.2:5555**`吗？
可否提供环境变量使用 `-e` 参数直接运行这样用起来更简易。

**Comment by sljeff** [comment]
```bash
ehco -l $YOUR_ENV1 -r $YOUR_ENV2
```

这样？

**Comment by olperson** [comment]
> ```shell
> ehco -l $YOUR_ENV1 -r $YOUR_ENV2
> ```
> 
> 这样？

是这样 不然好像只能进入docker运行 docker重启后可能无法保活进程

**Comment by Ehco1996** [comment]
@olperson ehco是支持环境变量挂载的 具体可以看这个文件 https://github.com/Ehco1996/ehco/blob/master/cmd/ehco/main.go
