### ISSUE TITLE
Release incorrectly tagged as `1.13`

### ISSUE THREAD

**Issue by bevanjkay** [Ehco1996/ehco#253]
The latest release on GitHub is tagged as `1.13` - https://github.com/Ehco1996/ehco/releases/tag/v1.13 - however, the version is `1.1.3`.

This is causing a mismatch in the release version and build version for - https://github.com/Homebrew/homebrew-core/pull/158252

**Comment by Ehco1996** [comment]
sorry... i will fix this

**Comment by Ehco1996** [comment]
Hi, the release and tag have been corrected on https://github.com/Ehco1996/ehco/releases/tag/v1.1.3.
Can you inform me about how I can restart the pull request process?

**Comment by bevanjkay** [comment]
Thank you. Re-running CI on our end now.

**Comment by chenrui333** [comment]
I guess 1.13 tag also needs to be removed as well (it would disrupt the downstream livecheck :) )

<img width="549" alt="image" src="https://github.com/Ehco1996/ehco/assets/1580956/e63a3a30-569f-40bc-8e44-6865028c4032">

**Comment by chenrui333** [comment]
cc @Ehco1996
