### ISSUE TITLE
json配置文件读取失败

### ISSUE THREAD

**Issue by wespochac** [Ehco1996/ehco#257]
不知道是个人问题还是大家都有这情况，1.1.2的配置文件，更新版本后读取失败了，回退到1.1.2和之前的版本都可以读取

**Comment by Ehco1996** [comment]
应该不会,配置一直是兼容的

可以贴一下失败配置文件上来

**Comment by wespochac** [comment]
配置范例如下

{
  "enable_ping": false,

  "relay_configs": [ 
        {   
   "listen": "0.0.0.0:11110",
      "listen_type": "raw",
      "transport_type": "raw",
      "tcp_remotes": ["0.0.0.0:443"],
      "udp_remotes": ["0.0.0.0:443"]
           }
   ]
}

自启动服务如下
[Unit]
Description=ehco
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Type=simple
User=root
Restart=always
RestartSec=5
DynamicUser=true
ExecStart=/usr/bin/ehco -c /etc/ehco/config.json

[Install]
WantedBy=multi-user.target

**Comment by Ehco1996** [comment]
我用这个配置文件测试了一下貌似没报错

```
❯ go run cmd/ehco/main.go -c test.json
2024-01-03T20:02:06+09:00	info	Start to watch relay config test.json
2024-01-03T20:02:06+09:00	info	relay	Start TCP relay Server <At=0.0.0.0:11110 Over=raw TCP-To=[0.0.0.0:443] UDP-To=[0.0.0.0:443] Through=raw>
2024-01-03T20:02:06+09:00	info	relay	Start UDP relay Server <At=0.0.0.0:11110 Over=raw TCP-To=[0.0.0.0:443] UDP-To=[0.0.0.0:443] Through=raw>
```

你的报错是 ehco 返回的么？

**Comment by wespochac** [comment]
是的，报 g.libc版本缺失，是不是编译的版本无法在 centos7 上运行？

**Comment by Ehco1996** [comment]
> 是的，报 g.libc版本缺失，是不是编译的版本无法在 centos7 上运行？

是的, cent7 上的 glibc 的版本太低了

**Comment by wespochac** [comment]
有办法解决吗？我试了一下 debian11 也报同样的错误

**Comment by Ehco1996** [comment]
> 有办法解决吗？我试了一下 debian11 也报同样的错误

需要自己升级一下 glibc, 或者用 docker 跑吧
