### ISSUE TITLE
Removing release v1.13

### ISSUE THREAD

**Issue by timsutton** [Ehco1996/ehco#275]
👋 Hi, I have been assisting with some homebrew formula maintenance in homebrew/core. I noticed there is this oddly-numbered release `v1.13` in this repo: https://github.com/Ehco1996/ehco/releases/tag/v1.13. It throws of the "live check" that brew uses to check for newer versions of upstream projects.

I wondered whether this release was intentional, and if not, is it possible to delete it? Thanks for your time!

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/159988 cc @Ehco1996

**Comment by Ehco1996** [comment]
Thank you very much @timsutton @chenrui333

All the tags and releases that were not aligned with semver were deleted.
