### ISSUE TITLE
关于转发DDNS

### ISSUE THREAD

**Issue by Cyrker** [Ehco1996/ehco#29]
你好！我想问一下转发DDNS的话，多久刷新一次DDNS的缓存呢？
看了一遍readme好像没看到有写关于这个的，所以来问一下

**Comment by Ehco1996** [comment]
@Cyrker 
是默认的dns缓存的时间

**Comment by a1328788808** [comment]
@Ehco1996 可以增加一个指定[dns:port]的功能吗？这样国内可以用自建的非标端口dns减少缓存时间。

**Comment by Ehco1996** [comment]
> @Ehco1996 可以增加一个指定[dns:port]的功能吗？这样国内可以用自建的非标端口dns减少缓存时间。

目前这个还不在开发计划中，需要的话可以自己提 pr，改动应该不会很多
