### ISSUE TITLE
Clarifying `sub_configs` purpose

### ISSUE THREAD

**Issue by NEK-RA** [Ehco1996/ehco#290]
Hi.

I've noticed you provided `sub_configs` field for the nightly version, but in readme it's just in context of load balancer proxy for remote clash configs (if translator haven't broken meaning).

Is it going to be only for mentioned purpose, or are you going to introduce ehco subconfigs later as well (which will allow to split one big config into few smaller)?

Thanks

**Comment by Ehco1996** [comment]
Regarding the sub_configs feature you mentioned, indeed, starting from version v1.1.4-dev(nightly), we introduced this feature primarily to support reading proxy configurations from Clash Proxy Providers and converting them into ehco's relay configurations. This functionality is designed to enable ehco to serve as a front proxy client, providing features such as load balancing and traffic monitoring.

As for your question about introducing additional sub-configurations (such as ehco sub-configs) to split one large configuration file into several smaller ones, we are indeed considering expanding the sub_configs feature to support more flexible configuration management. We recognize that as user configurations become increasingly complex, offering more flexible ways to manage configurations will be very beneficial to our users.

Currently, the sub_configs feature is focused on integration with Clash Proxy Providers, but we are actively exploring other potential uses, including but not limited to ehco sub-configurations. Our goal is to make ehco a more powerful and flexible tool to meet our users' growing needs.

**Comment by NEK-RA** [comment]
Thanks for explanation.
Since this was quite general question, I guess this issue may be closed. Otherwise, if you would like to keep it opened for anything related in future, how should I rename it?
