### ISSUE TITLE
用ehco做普通udp转发会出现上行极慢的情况

### ISSUE THREAD

**Issue by mandymak** [Ehco1996/ehco#30]
用gost没有这个问题。

**Comment by Ehco1996** [comment]
@mandymak  不好意思才看见

**Comment by mandymak** [comment]
@Ehco1996 运行ehco -l 0.0.0.0:11701 -r xxx.xxx.com:1701然后客户端通过这个连上l2tp在speedtest.net测的速，相同机器相同线路相同方法相同时间段用gost就没有问题。下行一忉正常，就上行出现问题。

**Comment by Ehco1996** [comment]
@mandymak  可以提供转发时 ehco端的日志么？

**Comment by mandymak** [comment]
![ehco](https://user-images.githubusercontent.com/26195499/104397191-3ac70700-5587-11eb-8a96-77acc9ef9cb4.jpg)

因为我这边的用途需要把程序改名运行

**Comment by Ehco1996** [comment]
这段时间有点忙，我空下来会尝试在本地复现一下

**Comment by mandymak** [comment]
好的，非常感谢！

**Comment by Ehco1996** [comment]
<img width="392" alt="截屏2021-01-22 上午7 53 35" src="https://user-images.githubusercontent.com/24697284/105429014-92eac100-5c8b-11eb-834f-04356465cd2a.png">

@mandymak 
我试了一下转发openvpn，感觉速度还挺快的？

l2tp我没有服务器可以测试，所以不知道该怎么复现
