### ISSUE TITLE
负载均衡不是很均衡

### ISSUE THREAD

**Issue by Ehco1996** [Ehco1996/ehco#31]
换一下算法

**Comment by Num0** [comment]
请问lb_remotes模式下设几个节点是最适宜的？
我自己尝试了2个节点负载均衡还正常的，但设置4个节点负载均衡的话就会莫名其妙卡住，每个节点都没问题的

**Comment by Ehco1996** [comment]
@Num0  的确有点问题,目前在重构了，下面几个版本会修掉的

**Comment by Ehco1996** [comment]
@Num0 新的版本应该已经修复了,可以试试

**Comment by Num0** [comment]
> @Num0 新的版本应该已经修复了,可以试试

测试了一下，没发现什么问题。感谢您提供了这么好用的工具，祝新春快乐

**Comment by Ehco1996** [comment]
reopen

**Comment by Ehco1996** [comment]
考虑用[round-robin](https://github.com/hlts2/round-robin/blob/master/round_robin.go) 实现一下
