### ISSUE TITLE
可以关闭ping吗

### ISSUE THREAD

**Issue by Num0** [Ehco1996/ehco#39]
希望能有关闭探针的功能，谢谢。

**Comment by Ehco1996** [comment]
好的 下次更新加上

**Comment by Ehco1996** [comment]
@Num0  我突然想起来现在只需要将 `web_port`设置为空就能关闭ping了， 但是这样所有的metrics监控也都没了

你觉得需要单独拆一个配置出来么？

**Comment by Num0** [comment]
谢谢指导，没有特别实际与迫切的需求，单纯是强迫症使然。
