### ISSUE TITLE
prebuild binaries are not able to run in Alpine Linux

### ISSUE THREAD

**Issue by hronro** [Ehco1996/ehco#43]
prebuild binaries from GitHub Releases are not static linked executable, so it can not run in Alpine Linux.

**Comment by Ehco1996** [comment]
@hronro 

you can use this [dockerfile](https://github.com/Ehco1996/ehco/blob/master/build/Dockerfile) to get `CGO_ENABLED=0` build binary

if you have interested in  making this in  github release , welcome to open PR
