### ISSUE TITLE
关于ehco各中转流量统计的API

### ISSUE THREAD

**Issue by sjlleo** [Ehco1996/ehco#47]
感谢作者提供这么棒的中转工具！

因为我是一直独立使用`Ehco`搭建隧道的，所以我一直在查找`Ehco`自身是否存在一个`WEB API`可以直接输出每个转发的流量总计。我在阅读了`ehco/internal/web`的代码中，看到了在`traffic_metrics.go`中有提到，但是我似乎并没有在`server.go`的`route`中找到有关可以直接提供流量统计的`API`入口。

另外我在`ehco/monitor`看到了一个`dashboard`，不仅可以输出Ping值，也可以输出流量总计，您知道这个面板是如何部署的吗？还是说需要搭配您的`django-sspanel`一起食用哦？

目前我的临时解决方案是只能通过系统级的`iptables`对端口的入站和出站流量进行统计，如果`Ehco`自身有这样的`WEB API`或者以`cli`的形式可以输出结果的话就再好不过了。

非常感谢！

**Comment by Ehco1996** [comment]
1. 可以通过 prometheus 收集流量的使用信箱，是有相关的接口的
2. dashboard 是 grafana 可以自己查一下

**Comment by sjlleo** [comment]
了解，非常感谢！
