### ISSUE TITLE
OP软路由里运行ehco DOCKER做中转机的问题

### ISSUE THREAD

**Issue by zzlinwq** [Ehco1996/ehco#72]
OP软路由里运行ehco DOCKER做中转机，如何通过mwss隧道转发5008端口到落地机2.2.2.2的443端口呢？

**Comment by zzlinwq** [comment]
OP软路由直接接光猫拨号上网，软路由IP为192.168.1.1，ehco DOCKE网络模式为host

**Comment by zzlinwq** [comment]
![捕获1](https://user-images.githubusercontent.com/36132083/149175604-565e9a35-ce91-4449-bfbd-63a937f303e5.PNG)

**Comment by zzlinwq** [comment]
如何通过mwss隧道转发5008端口到落地机2.2.2.2的443端口呢？具体DOCKER命令是什么呢？

**Comment by Ehco1996** [comment]
you can try read readme first, this is fully documented in example
