### ISSUE TITLE
wss  mwss 已经不好用了

### ISSUE THREAD

**Issue by 110560** [Ehco1996/ehco#87]
具体表现正常运行一段时间 中转机端口不通，必须重启一下程序，又恢复。，过一段时间又不通，，
 使用gost 转发没有这个问题

**Comment by ZJahon** [comment]
这个应该是软件产生的bug吧

**Comment by Ehco1996** [comment]
@110560 

可能是 bug，有日志能提供一下么

**Comment by Neurotoxinw** [comment]
同！应该是新版刚出现的问题，最近十几天一直莫名断线，排查了机子好久，结果昨天突然想到是不是转发的问题然后换回老版本之后就好了

**Comment by Ehco1996** [comment]
@Neurotoxinw @110560 尝试在 master 分支修复了这个问题，可以试试看

**Comment by Ehco1996** [comment]
replaced by https://github.com/Ehco1996/ehco/issues/98

**Comment by Ehco1996** [comment]
replaced by https://github.com/Ehco1996/ehco/issues/98
