### ISSUE TITLE
用ehco直连方式不行了吗

### ISSUE THREAD

**Issue by ZJahon** [Ehco1996/ehco#88]
中转机报错：
block remote node for 1000 times label=-64.156.14.143:2457 remote=64.156.14.143:2457                                                                                                              
dial error: dial tcp 64.156.14.143:2457: i/o timeout                                                                                                                                                   
HandleTCPConn meet error from:172.17.0.1:45020 to:64.156.14.143:2457 err:dial tcp 64.156.14.143:2457: i/o timeout

**Comment by Ehco1996** [comment]
这个是本机到 64.156.14.143 的网络有问题了，可以手动检查一下
