### ISSUE TITLE
wss隧道下无法中转udp

### ISSUE THREAD

**Issue by smallcat233** [Ehco1996/ehco#9]
使用软件：SSRR
出现的问题：开启udp转发后无法建立tcp链接，关闭udp转发后tcp正常建立连接。

**Comment by Ehco1996** [comment]
目前隧道还不不止透传udp

但是应该不影响tcp的使用才对。

你怎么使用的，请附上
* ssr的启动配置
* ehco中转端的配置
* ehco接受端的配置
