### ISSUE TITLE
ehco对接sspanel失败

### ISSUE THREAD

**Issue by frankniubi** [Ehco1996/ehco#99]
[cfg] Load Config From http:https://****/api/ehco_relay_config/1/?token=****[]
[web] Start Web Server at http://0.0.0.0:40080/
panic: runtime error: integer divide by zero

goroutine 27 [running]:
github.com/Ehco1996/ehco/internal/web.(*PingGroup).Run(0xc0001c5ce0)
        github.com/Ehco1996/ehco/internal/web/ping_metrics.go:123 +0x17a
created by github.com/Ehco1996/ehco/internal/web.registerMetrics
        github.com/Ehco1996/ehco/internal/web/server.go:52 +0x29b

系统Debian 11; GoLang版本1.17

**Comment by Ehco1996** [comment]
@frankniubi 感谢提供，是个 bug，在 master 版本已经修复了
